version: '3'

services:
  app:
    container_name: app
    build: ./
    volumes:
      - ./src/easyAdmin:/home/easyAdmin
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./src/easyAdmin:/home/easyAdmin
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    container_name: php
    image: php:7.2-fpm
    volumes:
      - ./src/easyAdmin:/home/easyAdmin
      - ./phpini/php-ini/php.ini:/usr/local/etc/php/conf.d/php.ini

  mariadb:
    container_name: mariadb
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd6421

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8765:80
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd6421
      UPLOAD_LIMIT: 300000000
    depends_on:
      - mariadb

